### PR TITLE
[#131] Use ruff for linter.

### LINKED ISSUE #131: Replace pycodestyle with ruff
T5651 task was created by danuker on 2021-06-01 11:36:48Z.
Last changed on 2021-06-01 15:42:02Z.

After migrating scame to Py3, remove pycodestyle, and instead of it use black, pyupgrade, and isort.

This is related to [#134](https://github.com/chevah/compat/issues/134) because our old pycodestyle 2.3.1. shows a warning on py3.

pyflakes and pylint need an update also because they throw errors under Py3.8; discuss with Adi whether to update or remove them.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

Fixes #131

Ruff has autoamtic code formating.

Changes
=======

Enable ruff config and run it on the existing code.

How to try and test the changes
===============================

reviewers: @dumol 

You can now use `./pythia.sh fix` to automatically reformat the code.
We will no longer have to worry about manually formting our code to please the linter.

IDEs have various integration with ruff.

`./pythia.sh lint` continue to works

more of a FYI.

### CODE REVIEW

**Comment by dumol** [comment]
> more of a FYI.

ACK.

**Comment by adiroiban** [comment]
thanks for the review. I plan to slowly add `ruff` to `chevah/server` 

the main part if auto-formating. You no longer have to worry about long lines or wrong paranthesis identation ... the code is auto-formated according to the standard

**Comment by dumol** [comment]
Just to be clear, I didn't actually review this. I've tried to look at the changes, but there were so many small ones…

I wonder, were most of these the result of auto-formatting with `ruff`?

**Comment by adiroiban** [comment]
That's ok. 99% if the changes were automated.

This was more of a FYI that a new tool is used.

**Pull request merged**
