### PR TITLE
[#3437] Add code coverage reporting via codecov.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

This add support for coverage reporting via codecov.

I hope that compat is pretty small and codecov can handle it

As a start, I want to use the coverage to make sure that we have 100% for our test code. This will make sure that all testing code is executed and we don't have tests code which we think is executed, but is not.

change
======

update build system

as a drive by I added the github template and paver.sh

How to test
=========

reviewers: @alibotean @brunogola 

to have some diff, I have pushed my local coverage results as being from master.

https://codecov.io/gh/chevah/compat/pull/59?src=pr

check that changes make sense

```
paver test_review 59
```

### CODE REVIEW

**Comment by adiroiban** [comment]
needs-review

**Comment by brunogola** [comment]
i get a 404 trying to access https://codecov.io/gh/chevah/compat/branch/3437-codecov  and a message saying:

```
Private Repository Access

Currently Codecov has access to public repositories but not private repositories.

Grant Codecov access to private repositories
```

**Comment by adiroiban** [comment]
> i get a 404 trying to access https://codecov.io/gh/chevah/compat/branch/3437-codecov and a message saying:

The url is wrong ... it used to work, but I don't know what happend... the new url is  https://codecov.io/gh/chevah/compat/pull/59?src=pr

thanks

**Comment by alibotean** [comment]
changes-approved

**Comment by brunogola** [comment]
changes-approved

**Pull request closed without merging**
