### PR TITLE
[#5311] Shorter OS names.

### PR DESCRIPTION
**Pull request by dumol**
Scope
=====

`compat` tests do not pass with the shorter win OS name, which prevents testing new `python-package` builds successfully on Windows slaves.

Changes
=======

Updated paver stuff from `python-package`.

How to try and test the changes
===============================

reviewers: **WIP**

### CODE REVIEW

**Comment by adiroiban** [comment]
Thanks for working on this..
I think that I have not fixed the getPythonLibPath in brink... or something is wrong there, as on windows it checkes for Unix style 'site-packages' folders.

I can look at this

**Comment by adiroiban** [comment]
I have fixed brink and wrote a test for it https://github.com/chevah/brink/commit/960c99d2d96f9286c6e707510bfe01ca8b747de6

**Comment by dumol** [comment]
> I have fixed brink and wrote a test for it [chevah/brink@960c99d](https://github.com/chevah/brink/commit/960c99d2d96f9286c6e707510bfe01ca8b747de6)

Thanks! Compat tests are looking good now…

"Required" slaves list should be updated here too with `alpine-310` and `amzn-2` for wholesome greenness. :-]

**Comment by adiroiban** [comment]
Done. If you are happy with the code, you can merge it without extra review.
Thanks!

**Pull request merged**
