### PR TITLE
[#692] Add support for Python 3.11.

### LINKED ISSUE #692: Get python 3.11 working

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

Fixes #692

This updates compat to work with Python 3.11.

Changes
=======

Use a newer brink that contains the nose patching for 3.11

How to try and test the changes
===============================

reviewers: @dumol  

more of a FYI

this is to make sure CI is green on 3.11

### CODE REVIEW

**Comment by adiroiban** [comment]
@dumol can you please review the list of supported OSes for pythia + chevah/compat and see what needs to be done to make this green.

thanks

needs-review

**Review by dumol — APPROVED** [review]
Some minor fixes for Docker-based testing in my commit above.

Notice that testing specifically on a clone of RHEL 8.2 is no longer required, as we no longer link to the system OpenSSL libs on RHEL 8.

**Comment by dumol** [comment]
If you merge this into master, I could try re-enabling compat tests in Pythia.

**Comment by adiroiban** [comment]
I will try to get this merged... this dependes on #132  but that PR is now open for review.
That is the main transition from 2.7 to 3.8

This code over here is the transition from 3.8 to 3.11

thanks

**Pull request merged**
