### PR TITLE
Fix placeholder attributes for virtual folders.

### PR DESCRIPTION
**Pull request by adiroiban**
Scope
=====

This fix the attributes for virtual folder to be returned as directory mode.

Why we got this
============

* Bad automated tests.

Changes
=======

Fix attribute mode to return the same value as _getPlaceholderStatus

As a drive-by change I have updated the brink.sh script.

How to try and test the changes
===============================

reviewers: @dumol 

The actual test can be done in chevah/server

### CODE REVIEW

**Comment by adiroiban** [comment]
@dumol there is a strange failure on GitHub Actions VMs for Ubuntu 18.04  https://github.com/chevah/compat/pull/101/checks?check_run_id=947613149

```
Installing base requirements: pip==20.1.1 chevah-brink==0.74.2 paver==1.2.4.
build-compat/bin/python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by build-compat/bin/python)
build-compat/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by build-compat/bin/python)
Failed to install pip==20.1.1 chevah-brink==0.74.2 paver==1.2.4.
```

**Comment by adiroiban** [comment]
needs-review

**Comment by dumol** [comment]
> @dumol there is a strange failure on GitHub Actions VMs for Ubuntu 18.04 https://github.com/chevah/compat/pull/101/checks?check_run_id=947613149
> 
> ```
> Installing base requirements: pip==20.1.1 chevah-brink==0.74.2 paver==1.2.4.
> build-compat/bin/python: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by build-compat/bin/python)
> build-compat/bin/python: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by build-compat/bin/python)
> Failed to install pip==20.1.1 chevah-brink==0.74.2 paver==1.2.4.
> ```

The issue doesn't reproduce on our slaves. And judging by when it started to fail, I suspect the Ubuntu 18.04 image somehow got corrupted on GitHub's side.

Can you add the tmux hack here too, so that we can try to debug?

**Comment by dumol** [comment]
Other than that…

**changes-approved**

**Comment by adiroiban** [comment]
I have pushed a commit with the tmate rule.
You will need to make a new commit with tmake enabled.

Please see why we got the glibc error. Maybe also enable ubuntu-18.04 inside the python-package GitHub Action workflow.

Thanks!

**Comment by dumol** [comment]
Thanks!

I found the issue to be caused by GitHub's "cache" action's copy of `build-compat`. Slightly changing `pavement.py` triggered a cache rebuild and all builds are green again.

Obligatory reference: _There are only two hard things in Computer Science: cache invalidation and naming things._

**Comment by adiroiban** [comment]
Thanks. I need to add brink.conf as a key to the cache, not only OS + pavement.py file. Thanks :)

**Comment by adiroiban** [comment]
@dumol  I hope that compat master will be  now  green on GitHub Actions and Travis

**Comment by dumol** [comment]
> @dumol I hope that compat master will be now green on GitHub Actions and Travis

Looks like it… Thanks!

**Pull request merged**
