### PR TITLE
[bad-id] Add support for UNC and links to Windows Shares.

### PR DESCRIPTION
**Pull request by adiroiban**
see https://github.com/chevah/compat/pull/88

### CODE REVIEW

**Comment by adiroiban** [comment]
coverator still not working, but the other slaves are green.

will look at coverator later, but that is a separte issue

needs-review

**Comment by hcs0** [comment]
Looks like it is the wrong ticket ID - could be https://trac.chevah.com/ticket/3543

**Comment by adiroiban** [comment]
> Looks like it is the wrong ticket ID - could be https://trac.chevah.com/ticket/3543

3543 is about allowing direct access to the UNC, not via symbolic links.

This ticket is about creating a symbolic link to an UNC and using that simbolic link.

The symbolic link has normal local path.

So for now, you can access the files from \\server\share-name via c:\users\some-link 

3543 is about being able to access the \\server\share-name directly without the need for a symbolic link

**Comment by hcs0** [comment]
@adiroiban 4861 is writing a user guide (recursive vs non recursive) https://trac.chevah.com/ticket/4861

**Pull request closed without merging**
